from _typeshed import Incomplete
from sympy.polys.domains.characteristiczero import CharacteristicZero
from sympy.polys.domains.field import Field
from sympy.polys.domains.simpledomain import SimpleDomain

__all__ = ['ComplexField']

class ComplexField(Field, CharacteristicZero, SimpleDomain):
    rep: str
    is_ComplexField: bool
    is_CC: bool
    is_Exact: bool
    is_Numerical: bool
    has_assoc_Ring: bool
    has_assoc_Field: bool
    @property
    def has_default_precision(self): ...
    @property
    def precision(self): ...
    @property
    def dps(self): ...
    @property
    def tolerance(self): ...
    zero: Incomplete
    one: Incomplete
    def __init__(self, prec=..., dps: Incomplete | None = None, tol: Incomplete | None = None) -> None: ...
    @property
    def tp(self): ...
    def dtype(self, x, y: int = 0): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def to_sympy(self, element): ...
    def from_sympy(self, expr): ...
    def from_ZZ(self, element, base): ...
    def from_ZZ_gmpy(self, element, base): ...
    def from_ZZ_python(self, element, base): ...
    def from_QQ(self, element, base): ...
    def from_QQ_python(self, element, base): ...
    def from_QQ_gmpy(self, element, base): ...
    def from_GaussianIntegerRing(self, element, base): ...
    def from_GaussianRationalField(self, element, base): ...
    def from_AlgebraicField(self, element, base): ...
    def from_RealField(self, element, base): ...
    def from_ComplexField(self, element, base): ...
    def get_ring(self) -> None: ...
    def get_exact(self): ...
    def is_negative(self, element): ...
    def is_positive(self, element): ...
    def is_nonnegative(self, element): ...
    def is_nonpositive(self, element): ...
    def gcd(self, a, b): ...
    def lcm(self, a, b): ...
    def almosteq(self, a, b, tolerance: Incomplete | None = None): ...
    def is_square(self, a): ...
    def exsqrt(self, a): ...
