from _typeshed import Incomplete
from sympy.polys.domains.domain import Domain

__all__ = ['CompositeDomain']

class CompositeDomain(Domain):
    is_Composite: bool
    gens: Incomplete
    ngens: Incomplete
    symbols: Incomplete
    domain: Incomplete
    def inject(self, *symbols): ...
    def drop(self, *symbols): ...
    def set_domain(self, domain): ...
    @property
    def is_Exact(self): ...
    def get_exact(self): ...
    @property
    def has_CharacteristicZero(self): ...
    def characteristic(self): ...
