from sympy.polys.domains.ring import Ring

__all__ = ['Field']

class Field(Ring):
    is_Field: bool
    is_PID: bool
    def get_ring(self) -> None: ...
    def get_field(self): ...
    def exquo(self, a, b): ...
    def quo(self, a, b): ...
    def rem(self, a, b): ...
    def div(self, a, b): ...
    def gcd(self, a, b): ...
    def lcm(self, a, b): ...
    def revert(self, a): ...
    def is_unit(self, a): ...
