from _typeshed import Incomplete
from sympy.polys.domains.compositedomain import CompositeDomain
from sympy.polys.domains.field import Field

__all__ = ['FractionField']

class FractionField(Field, CompositeDomain):
    is_FractionField: bool
    is_Frac: bool
    has_assoc_Ring: bool
    has_assoc_Field: bool
    field: Incomplete
    dtype: Incomplete
    gens: Incomplete
    ngens: Incomplete
    symbols: Incomplete
    domain: Incomplete
    dom: Incomplete
    def __init__(self, domain_or_field, symbols: Incomplete | None = None, order: Incomplete | None = None) -> None: ...
    def new(self, element): ...
    @property
    def zero(self): ...
    @property
    def one(self): ...
    @property
    def order(self): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def to_sympy(self, a): ...
    def from_sympy(self, a): ...
    def from_ZZ(K1, a, K0): ...
    def from_ZZ_python(K1, a, K0): ...
    def from_QQ(K1, a, K0): ...
    def from_QQ_python(K1, a, K0): ...
    def from_ZZ_gmpy(K1, a, K0): ...
    def from_QQ_gmpy(K1, a, K0): ...
    def from_GaussianRationalField(K1, a, K0): ...
    def from_GaussianIntegerRing(K1, a, K0): ...
    def from_RealField(K1, a, K0): ...
    def from_ComplexField(K1, a, K0): ...
    def from_AlgebraicField(K1, a, K0): ...
    def from_PolynomialRing(K1, a, K0): ...
    def from_FractionField(K1, a, K0): ...
    def get_ring(self): ...
    def is_positive(self, a): ...
    def is_negative(self, a): ...
    def is_nonpositive(self, a): ...
    def is_nonnegative(self, a): ...
    def numer(self, a): ...
    def denom(self, a): ...
    def factorial(self, a): ...
