from _typeshed import Incomplete
from sympy.polys.domains.groundtypes import GMPYRational
from sympy.polys.domains.rationalfield import RationalField

__all__ = ['GMPYRationalField']

class GMPYRationalField(RationalField):
    dtype = GMPYRational
    zero: Incomplete
    one: Incomplete
    tp: Incomplete
    alias: str
    def __init__(self) -> None: ...
    def get_ring(self): ...
    def to_sympy(self, a): ...
    def from_sympy(self, a): ...
    def from_ZZ_python(K1, a, K0): ...
    def from_QQ_python(K1, a, K0): ...
    def from_ZZ_gmpy(K1, a, K0): ...
    def from_QQ_gmpy(K1, a, K0): ...
    def from_GaussianRationalField(K1, a, K0): ...
    def from_RealField(K1, a, K0): ...
    def exquo(self, a, b): ...
    def quo(self, a, b): ...
    def rem(self, a, b): ...
    def div(self, a, b): ...
    def numer(self, a): ...
    def denom(self, a): ...
    def factorial(self, a): ...
