from _typeshed import Incomplete
from sympy.polys.domains.compositedomain import CompositeDomain
from sympy.polys.domains.field import Field
from sympy.polys.polyclasses import DMF

__all__ = ['FractionField']

class FractionField(Field, CompositeDomain):
    dtype = DMF
    is_FractionField: bool
    is_Frac: bool
    has_assoc_Ring: bool
    has_assoc_Field: bool
    ngens: Incomplete
    zero: Incomplete
    one: Incomplete
    domain: Incomplete
    symbols: Incomplete
    def __init__(self, dom, *gens) -> None: ...
    def set_domain(self, dom): ...
    def new(self, element): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def to_sympy(self, a): ...
    def from_sympy(self, a): ...
    def from_ZZ(K1, a, K0): ...
    def from_ZZ_python(K1, a, K0): ...
    def from_QQ_python(K1, a, K0): ...
    def from_ZZ_gmpy(K1, a, K0): ...
    def from_QQ_gmpy(K1, a, K0): ...
    def from_RealField(K1, a, K0): ...
    def from_GlobalPolynomialRing(K1, a, K0): ...
    def from_FractionField(K1, a, K0): ...
    def get_ring(self): ...
    def poly_ring(self, *gens) -> None: ...
    def frac_field(self, *gens) -> None: ...
    def is_positive(self, a): ...
    def is_negative(self, a): ...
    def is_nonpositive(self, a): ...
    def is_nonnegative(self, a): ...
    def numer(self, a): ...
    def denom(self, a): ...
    def factorial(self, a): ...
