from _typeshed import Incomplete
from sympy.polys.domains.groundtypes import PythonRational
from sympy.polys.domains.rationalfield import RationalField

__all__ = ['PythonRationalField']

class PythonRationalField(RationalField):
    dtype = PythonRational
    zero: Incomplete
    one: Incomplete
    alias: str
    def __init__(self) -> None: ...
    def get_ring(self): ...
    def to_sympy(self, a): ...
    def from_sympy(self, a): ...
    def from_ZZ_python(K1, a, K0): ...
    def from_QQ_python(K1, a, K0): ...
    def from_ZZ_gmpy(K1, a, K0): ...
    def from_QQ_gmpy(K1, a, K0): ...
    def from_RealField(K1, a, K0): ...
    def numer(self, a): ...
    def denom(self, a): ...
