from sympy.polys.domains.domain import Domain

__all__ = ['Ring']

class Ring(Domain):
    is_Ring: bool
    def get_ring(self): ...
    def exquo(self, a, b): ...
    def quo(self, a, b): ...
    def rem(self, a, b): ...
    def div(self, a, b): ...
    def invert(self, a, b): ...
    def revert(self, a): ...
    def is_unit(self, a): ...
    def numer(self, a): ...
    def denom(self, a): ...
    def free_module(self, rank) -> None: ...
    def ideal(self, *gens): ...
    def quotient_ring(self, e): ...
    def __truediv__(self, e): ...
