from .util import new as new
from sympy.utilities.iterables import sift as sift

def rm_id(isid, new=...): ...
def glom(key, count, combine): ...
def sort(key, new=...): ...
def distribute(A, B): ...
def subs(a, b): ...
def unpack(expr): ...
def flatten(expr, new=...): ...
def rebuild(expr): ...
