from _typeshed import Incomplete
from cvxpy import atoms as atoms
from cvxpy.atoms.affine.diag import diag_vec as diag_vec
from cvxpy.atoms.affine.promote import promote as promote
from cvxpy.atoms.affine.upper_tri import upper_tri as upper_tri
from cvxpy.constraints.psd import PSD as PSD
from cvxpy.expressions.constants.parameter import Parameter as Parameter
from cvxpy.expressions.variable import Variable as Variable

def dist_ratio_sub(expr, t): ...
def mul_sup(expr, t): ...
def mul_sub(expr, t): ...
def ratio_sup(expr, t): ...
def ratio_sub(expr, t): ...
def length_sub(expr, t): ...
def sign_sup(expr, t): ...
def sign_sub(expr, t): ...
def gen_lambda_max_sub(expr, t): ...
def condition_number_sub(expr, t): ...

SUBLEVEL_SETS: Incomplete
SUPERLEVEL_SETS: Incomplete

def sublevel(expr, t): ...
def superlevel(expr, t): ...
