from _typeshed import Incomplete
from pyglet.window import Window

gl_lock: Incomplete

class ManagedWindow(Window):
    fps_limit: int
    default_win_args: Incomplete
    win_args: Incomplete
    Thread: Incomplete
    def __init__(self, **win_args) -> None: ...
    has_exit: bool
    def __event_loop__(self, **win_args) -> None: ...
    def close(self) -> None: ...
    def setup(self) -> None: ...
    def update(self, dt) -> None: ...
    def draw(self) -> None: ...
