[project]
name = "ncpol3sdpa"
version = "0.1.0"
description = "Python package for solving polynomial optimization problems"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvxpy>=1.6.3",
    "mypy>=1.15.0",
    "sympy>=1.13.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheels]
packages = ["src/ncpol3sdpa"]

[tool.ruff]
indent-width = 4
exclude = ["Exercises"]

[tool.ruff.lint]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.mypy]
strict = true