from sympy.assumptions.ask import Q as Q
from sympy.assumptions.cnf import Literal as Literal
from sympy.core.cache import cacheit as cacheit

def get_all_known_facts(): ...
def get_all_known_matrix_facts(): ...
def get_all_known_number_facts(): ...
def get_known_facts_dict(): ...
