from sympy.assumptions import Q as Q, ask as ask
from sympy.core import Add as Add, Basic as Basic, Expr as Expr, Mul as Mul, Pow as Pow, Rational as Rational, S as S
from sympy.core.logic import fuzzy_not as fuzzy_not
from sympy.logic.boolalg import Boolean as Boolean
from typing import Callable

def refine(expr, assumptions: bool = True): ...
def refine_abs(expr, assumptions): ...
def refine_Pow(expr, assumptions): ...
def refine_atan2(expr, assumptions): ...
def refine_re(expr, assumptions): ...
def refine_im(expr, assumptions): ...
def refine_arg(expr, assumptions): ...
def refine_sign(expr, assumptions): ...
def refine_matrixelement(expr, assumptions): ...

handlers_dict: dict[str, Callable[[Expr, Boolean], Expr]]
