from _typeshed import Incomplete
from sympy.assumptions import Q as Q, ask as ask
from sympy.core.basic import Basic as Basic

def make_eval_method(fact): ...

class AssumptionsWrapper(Basic):
    def __new__(cls, expr, assumptions: Incomplete | None = None): ...

def is_infinite(obj, assumptions: Incomplete | None = None): ...
def is_extended_real(obj, assumptions: Incomplete | None = None): ...
def is_extended_nonnegative(obj, assumptions: Incomplete | None = None): ...
