from _typeshed import Incomplete
from collections.abc import Generator
from sympy.combinatorics.permutations import Permutation as Permutation
from sympy.core.symbol import symbols as symbols
from sympy.matrices import Matrix as Matrix
from sympy.utilities.iterables import rotate_left as rotate_left, variations as variations

def symmetric(n) -> Generator[Incomplete]: ...
def cyclic(n) -> Generator[Incomplete]: ...
def alternating(n) -> Generator[Incomplete]: ...
def dihedral(n) -> Generator[Incomplete]: ...
def rubik_cube_generators(): ...
def rubik(n): ...
