from sympy.external.gmpy import gcd as gcd
from sympy.ntheory.factor_ import factorint as factorint
from sympy.utilities.misc import as_int as as_int

def is_nilpotent_number(n) -> bool: ...
def is_abelian_number(n) -> bool: ...
def is_cyclic_number(n) -> bool: ...
def groups_count(n): ...
