from sympy.combinatorics.group_constructs import DirectProduct as DirectProduct
from sympy.combinatorics.perm_groups import PermutationGroup as PermutationGroup
from sympy.combinatorics.permutations import Permutation as Permutation

def AbelianGroup(*cyclic_orders): ...
def AlternatingGroup(n): ...
def set_alternating_group_properties(G, n, degree) -> None: ...
def CyclicGroup(n): ...
def DihedralGroup(n): ...
def SymmetricGroup(n): ...
def set_symmetric_group_properties(G, n, degree) -> None: ...
def RubikGroup(n): ...
