from _typeshed import Incomplete
from sympy.testing.pytest import XFAIL as XFAIL
from typing import NamedTuple

def may_xfail(func): ...

class CompilerNotFoundError(FileNotFoundError): ...
class CompileError(Exception): ...

def get_abspath(path, cwd: str = '.'): ...
def make_dirs(path) -> None: ...
def missing_or_other_newer(path, other_path, cwd: Incomplete | None = None): ...
def copy(src, dst, only_update: bool = False, copystat: bool = True, cwd: Incomplete | None = None, dest_is_dir: bool = False, create_dest_dirs: bool = False): ...

class Glob(NamedTuple):
    pathname: Incomplete

class ArbitraryDepthGlob(NamedTuple):
    filename: Incomplete

def glob_at_depth(filename_glob, cwd: Incomplete | None = None): ...
def sha256_of_file(path, nblocks: int = 128): ...
def sha256_of_string(string): ...
def pyx_is_cplus(path): ...
def import_module_from_file(filename, only_if_newer_than: Incomplete | None = None): ...
def find_binary_of_command(candidates): ...
def unique_list(l): ...
