from _typeshed import Incomplete
from sympy.core.basic import Basic as Basic
from sympy.core.containers import Dict as Dict, Tuple as Tuple
from sympy.core.singleton import S as S
from sympy.tensor.array.mutable_ndim_array import MutableNDimArray as MutableNDimArray
from sympy.tensor.array.ndim_array import ImmutableNDimArray as ImmutableNDimArray, NDimArray as NDimArray
from sympy.utilities.iterables import flatten as flatten

class SparseNDimArray(NDimArray):
    def __new__(self, *args, **kwargs): ...
    def __getitem__(self, index): ...
    @classmethod
    def zeros(cls, *shape): ...
    def tomatrix(self): ...
    def reshape(self, *newshape): ...

class ImmutableSparseNDimArray(SparseNDimArray, ImmutableNDimArray):
    def __new__(cls, iterable: Incomplete | None = None, shape: Incomplete | None = None, **kwargs): ...
    def __setitem__(self, index, value) -> None: ...
    def as_mutable(self): ...

class MutableSparseNDimArray(MutableNDimArray, SparseNDimArray):
    def __new__(cls, iterable: Incomplete | None = None, shape: Incomplete | None = None, **kwargs): ...
    def __setitem__(self, index, value) -> None: ...
    def as_immutable(self): ...
    @property
    def free_symbols(self): ...
