from _typeshed import Incomplete
from cvxpy.atoms import abs as abs, max as max, maximum as maximum, norm1 as norm1, norm_inf as norm_inf, sum_largest as sum_largest
from cvxpy.reductions.canonicalization import Canonicalization as Canonicalization

class EliminatePwl(Canonicalization):
    def __init__(self, problem: Incomplete | None = None) -> None: ...
    def accepts(self, problem) -> bool: ...
    def apply(self, problem): ...
