from _typeshed import Incomplete
from sympy.core import Basic as Basic, Mul as Mul, PoleError as PoleError, S as S, expand_mul as expand_mul
from sympy.core.cache import cacheit as cacheit
from sympy.core.intfunc import ilcm as ilcm
from sympy.core.numbers import I as I, oo as oo
from sympy.core.symbol import Dummy as Dummy, Wild as Wild
from sympy.core.traversal import bottom_up as bottom_up
from sympy.functions import exp as exp, log as log
from sympy.series.order import Order as Order
from sympy.utilities.exceptions import SymPyDeprecationWarning as SymPyDeprecationWarning
from sympy.utilities.timeutils import timethis as timethis

timeit: Incomplete

def compare(a, b, x): ...

class SubsSet(dict):
    rewrites: Incomplete
    def __init__(self) -> None: ...
    def __getitem__(self, key): ...
    def do_subs(self, e): ...
    def meets(self, s2): ...
    def union(self, s2, exps: Incomplete | None = None): ...
    def copy(self): ...

def mrv(e, x): ...
def mrv_max3(f, expsf, g, expsg, union, expsboth, x): ...
def mrv_max1(f, g, exps, x): ...
def sign(e, x): ...
def limitinf(e, x): ...
def moveup2(s, x): ...
def moveup(l, x): ...
def calculate_series(e, x, logx: Incomplete | None = None): ...
def mrv_leadterm(e, x): ...
def build_expression_tree(Omega, rewrites): ...
def rewrite(e, Omega, x, wsym): ...
def gruntz(e, z, z0, dir: str = '+'): ...
