from sympy.core.cache import cacheit as cacheit
from sympy.core.expr import Expr as Expr
from sympy.core.singleton import S as S

class SeriesBase(Expr):
    @property
    def interval(self) -> None: ...
    @property
    def start(self) -> None: ...
    @property
    def stop(self) -> None: ...
    @property
    def length(self) -> None: ...
    @property
    def variables(self): ...
    @property
    def free_symbols(self): ...
    def term(self, pt): ...
    def __iter__(self): ...
    def __getitem__(self, index): ...
