from _typeshed import Incomplete
from collections.abc import Generator
from sympy.core.exprtools import factor_terms as factor_terms
from sympy.core.numbers import Integer as Integer, Rational as Rational
from sympy.core.singleton import S as S
from sympy.core.symbol import Dummy as Dummy
from sympy.utilities.misc import as_int as as_int

def continued_fraction(a) -> list: ...
def continued_fraction_periodic(p, q, d: int = 0, s: int = 1) -> list: ...
def continued_fraction_reduce(cf): ...
def continued_fraction_iterator(x) -> Generator[Incomplete]: ...
def continued_fraction_convergents(cf) -> Generator[Incomplete]: ...
