from .generate import primerange as primerange, sieve as sieve
from .primetest import isprime as isprime
from _typeshed import Incomplete
from sympy.external.gmpy import gcd as gcd, invert as invert, sqrt as sqrt
from sympy.utilities.misc import as_int as as_int

class Point:
    x_cord: Incomplete
    z_cord: Incomplete
    a_24: Incomplete
    mod: Incomplete
    def __init__(self, x_cord, z_cord, a_24, mod) -> None: ...
    def __eq__(self, other): ...
    def add(self, Q, diff): ...
    def double(self): ...
    def mont_ladder(self, k): ...

def ecm(n, B1: int = 10000, B2: int = 100000, max_curve: int = 200, seed: int = 1234): ...
