from sympy.external.gmpy import gcd as gcd, gcdext as gcdext
from sympy.ntheory.primetest import isprime as isprime
from sympy.polys.domains import ZZ as ZZ
from sympy.polys.galoistools import gf_crt as gf_crt, gf_crt1 as gf_crt1, gf_crt2 as gf_crt2
from sympy.utilities.misc import as_int as as_int

def symmetric_residue(a, m): ...
def crt(m, v, symmetric: bool = False, check: bool = True): ...
def crt1(m): ...
def crt2(m, v, mm, e, s, symmetric: bool = False): ...
def solve_congruence(*remainder_modulus_pairs, **hint): ...
