from _typeshed import Incomplete
from collections.abc import Generator
from sympy.utilities.misc import as_int as as_int

def binomial_coefficients(n): ...
def binomial_coefficients_list(n): ...
def multinomial_coefficients(m, n): ...
def multinomial_coefficients_iterator(m, n, _tuple=...) -> Generator[Incomplete, Incomplete]: ...
