from _typeshed import Incomplete
from sympy.concrete.expr_with_limits import ExprWithLimits as ExprWithLimits
from sympy.core.relational import Eq as Eq
from sympy.core.singleton import S as S

class ReorderError(NotImplementedError):
    def __init__(self, expr, msg) -> None: ...

class ExprWithIntLimits(ExprWithLimits):
    def change_index(self, var, trafo, newvar: Incomplete | None = None): ...
    def index(expr, x): ...
    def reorder(expr, *arg): ...
    def reorder_limit(expr, x, y): ...
    @property
    def has_empty_sequence(self): ...
