from _typeshed import Incomplete

__all__ = ['find_simple_recurrence_vector', 'find_simple_recurrence', 'rationalize', 'guess_generating_function_rational', 'guess_generating_function', 'guess']

def find_simple_recurrence_vector(l): ...
def find_simple_recurrence(v, A=..., N=...): ...
def rationalize(x, maxcoeff: int = 10000): ...
def guess_generating_function_rational(v, X=...): ...
def guess_generating_function(v, X=..., types=['all'], maxsqrtn: int = 2): ...
def guess(l, all: bool = False, evaluate: bool = True, niter: int = 2, variables: Incomplete | None = None): ...
