from .sets import FiniteSet as FiniteSet, Set as Set, SetKind as SetKind
from _typeshed import Incomplete
from sympy.core.logic import fuzzy_bool as fuzzy_bool
from sympy.core.parameters import global_parameters as global_parameters
from sympy.core.singleton import S as S

class PowerSet(Set):
    def __new__(cls, arg, evaluate: Incomplete | None = None): ...
    @property
    def arg(self): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    @property
    def kind(self): ...
