from .fancysets import ImageSet as ImageSet
from .sets import set_add as set_add, set_div as set_div, set_function as set_function, set_mul as set_mul, set_pow as set_pow, set_sub as set_sub
from _typeshed import Incomplete
from sympy.core import Expr as Expr
from sympy.core.decorators import call_highest_priority as call_highest_priority

class SetExpr(Expr):
    def __new__(cls, setarg): ...
    set: Incomplete
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __pow__(self, other): ...
    def __rpow__(self, other): ...
    def __truediv__(self, other): ...
    def __rtruediv__(self, other): ...
