from sympy.assumptions.cnf import CNF as CNF
from sympy.core.sorting import default_sort_key as default_sort_key
from sympy.logic.boolalg import Not as Not, Or as Or, conjuncts as conjuncts, disjuncts as disjuncts, to_cnf as to_cnf, to_int_repr as to_int_repr
from sympy.logic.inference import literal_symbol as literal_symbol, pl_true as pl_true

def dpll_satisfiable(expr): ...
def dpll(clauses, symbols, model): ...
def dpll_int_repr(clauses, symbols, model): ...
def pl_true_int_repr(clause, model={}): ...
def unit_propagate(clauses, symbol): ...
def unit_propagate_int_repr(clauses, s): ...
def find_pure_symbol(symbols, unknown_clauses): ...
def find_pure_symbol_int_repr(symbols, unknown_clauses): ...
def find_unit_clause(clauses, model): ...
def find_unit_clause_int_repr(clauses, model): ...
