from sympy.core import Add as Add, Mul as Mul, Pow as Pow, S as S
from sympy.core.basic import Basic as Basic
from sympy.core.expr import Expr as Expr
from sympy.core.numbers import oo as oo, zoo as zoo
from sympy.core.relational import is_ge as is_ge, is_gt as is_gt, is_le as is_le, is_lt as is_lt
from sympy.functions.elementary.miscellaneous import Max as Max, Min as Min
from sympy.logic.boolalg import And as And
from sympy.multipledispatch import dispatch as dispatch
from sympy.series.order import Order as Order
from sympy.sets.sets import FiniteSet as FiniteSet

class AccumulationBounds(Expr):
    is_extended_real: bool
    is_number: bool
    def __new__(cls, min, max): ...
    @property
    def min(self): ...
    @property
    def max(self): ...
    @property
    def delta(self): ...
    @property
    def mid(self): ...
    def __add__(self, other): ...
    __radd__ = __add__
    def __neg__(self): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, other): ...
    __rmul__ = __mul__
    def __truediv__(self, other): ...
    def __rtruediv__(self, other): ...
    def __pow__(self, other): ...
    def __rpow__(self, other): ...
    def __abs__(self): ...
    def __contains__(self, other) -> bool: ...
    def intersection(self, other): ...
    def union(self, other): ...
AccumBounds = AccumulationBounds
