from .matexpr import MatrixExpr as MatrixExpr
from .special import Identity as Identity, OneMatrix as OneMatrix, ZeroMatrix as ZeroMatrix
from sympy.core import S as S
from sympy.functions import KroneckerDelta as KroneckerDelta

class PermutationMatrix(MatrixExpr):
    def __new__(cls, perm): ...
    @property
    def shape(self): ...
    @property
    def is_Identity(self): ...
    def doit(self, **hints): ...

class MatrixPermute(MatrixExpr):
    def __new__(cls, mat, perm, axis=...): ...
    def doit(self, deep: bool = True, **hints): ...
    @property
    def shape(self): ...
