from sympy.core import Basic as Basic
from sympy.vector.operators import curl as curl, divergence as divergence, gradient as gradient

class Del(Basic):
    def __new__(cls): ...
    def gradient(self, scalar_field, doit: bool = False): ...
    __call__ = gradient
    def dot(self, vect, doit: bool = False): ...
    __and__ = dot
    def cross(self, vect, doit: bool = False): ...
    __xor__ = cross
