from _typeshed import Incomplete
from sympy.core.basic import Basic as Basic
from sympy.core.cache import cacheit as cacheit
from sympy.core.symbol import Str as Str
from sympy.vector.coordsysrect import CoordSys3D as CoordSys3D
from sympy.vector.vector import Vector as Vector

class Point(Basic):
    def __new__(cls, name, position=..., parent_point: Incomplete | None = None): ...
    def position_wrt(self, other): ...
    def locate_new(self, name, position): ...
    def express_coordinates(self, coordinate_system): ...
