class MatrixError(Exception): ...
class ShapeError(ValueError, MatrixError): ...
class NonSquareMatrixError(ShapeError): ...
class NonInvertibleMatrixError(ValueError, MatrixError): ...
class NonPositiveDefiniteMatrixError(ValueError, MatrixError): ...
