from sympy.core.kind import Kind as Kind, NumberKind as NumberKind
from sympy.core.mul import Mul as Mul

class MatrixKind(Kind):
    def __new__(cls, element_kind=...): ...

def num_mat_mul(k1, k2): ...
def mat_mat_mul(k1, k2): ...
