from _typeshed import Incomplete
from sympy.polys.domains.integerring import ZZ as ZZ
from sympy.polys.matrices import DomainMatrix as DomainMatrix
from sympy.polys.polytools import Poly as Poly

def smith_normal_form(m, domain: Incomplete | None = None): ...
def invariant_factors(m, domain: Incomplete | None = None): ...
def hermite_normal_form(A, *, D: Incomplete | None = None, check_rank: bool = False): ...
