from _typeshed import Incomplete
from sympy.utilities.exceptions import sympy_deprecation_warning as sympy_deprecation_warning

def threaded_factory(func, use_add): ...
def threaded(func): ...
def xthreaded(func): ...
def conserve_mpmath_dps(func): ...

class no_attrs_in_subclass:
    cls: Incomplete
    f: Incomplete
    def __init__(self, cls, f) -> None: ...
    def __get__(self, instance, owner: Incomplete | None = None): ...

def doctest_depends_on(exe: Incomplete | None = None, modules: Incomplete | None = None, disable_viewers: Incomplete | None = None, python_version: Incomplete | None = None, ground_types: Incomplete | None = None): ...
def public(obj): ...
def memoize_property(propfunc): ...
def deprecated(message, *, deprecated_since_version, active_deprecations_target, stacklevel: int = 3): ...
