from _typeshed import Incomplete

class Undecidable(ValueError): ...

def filldedent(s, w: int = 70, **kwargs): ...
def strlines(s, c: int = 64, short: bool = False): ...
def rawlines(s): ...

ARCH: Incomplete
HASH_RANDOMIZATION: Incomplete

def debug_decorator(func): ...
def debug(*args) -> None: ...
def debugf(string, args) -> None: ...
def find_executable(executable, path: Incomplete | None = None): ...
def func_name(x, short: bool = False): ...
def replace(string, *reps): ...
def translate(s, a, b: Incomplete | None = None, c: Incomplete | None = None): ...
def ordinal(num): ...
def as_int(n, strict: bool = True): ...
