from sympy.core import Dummy as Dummy, S as S, pi as pi
from sympy.functions.combinatorial.factorials import factorial as factorial
from sympy.functions.elementary.miscellaneous import sqrt as sqrt
from sympy.functions.elementary.trigonometric import cos as cos, sin as sin
from sympy.functions.special.gamma_functions import gamma as gamma
from sympy.polys.orthopolys import hermite_poly as hermite_poly, jacobi_poly as jacobi_poly, laguerre_poly as laguerre_poly, legendre_poly as legendre_poly
from sympy.polys.rootoftools import RootOf as RootOf

def gauss_legendre(n, n_digits): ...
def gauss_laguerre(n, n_digits): ...
def gauss_hermite(n, n_digits): ...
def gauss_gen_laguerre(n, alpha, n_digits): ...
def gauss_chebyshev_t(n, n_digits): ...
def gauss_chebyshev_u(n, n_digits): ...
def gauss_jacobi(n, alpha, beta, n_digits): ...
def gauss_lobatto(n, n_digits): ...
