from .entity import GeometryEntity as GeometryEntity
from .exceptions import GeometryError as GeometryError
from .point import Point as Point, Point2D as Point2D, Point3D as Point3D
from sympy import nsimplify as nsimplify
from sympy.core.containers import OrderedSet as OrderedSet
from sympy.core.exprtools import factor_terms as factor_terms
from sympy.core.function import Function as Function, expand_mul as expand_mul
from sympy.core.numbers import Float as Float
from sympy.core.singleton import S as S
from sympy.core.sorting import ordered as ordered
from sympy.core.symbol import Symbol as Symbol
from sympy.functions.elementary.miscellaneous import sqrt as sqrt
from sympy.polys.polytools import cancel as cancel
from sympy.utilities.iterables import is_sequence as is_sequence

def find(x, equation): ...
def are_coplanar(*e): ...
def are_similar(e1, e2): ...
def centroid(*args): ...
def closest_points(*args): ...
def convex_hull(*args, polygon: bool = True): ...
def farthest_points(*args): ...
def idiff(eq, y, x, n: int = 1): ...
def intersection(*entities, pairwise: bool = False, **kwargs): ...
