from _typeshed import Incomplete
from collections.abc import Generator
from sympy.core.numbers import Float as Float
from sympy.core.symbol import Dummy as Dummy
from sympy.utilities.lambdify import lambdify as lambdify

def is_valid(x): ...
def rescale(y, W, H, mi, ma): ...
def linspace(start, stop, num): ...
def textplot_str(expr, a, b, W: int = 55, H: int = 21) -> Generator[Incomplete]: ...
def textplot(expr, a, b, W: int = 55, H: int = 21) -> None: ...
