from _typeshed import Incomplete
from sympy.physics.vector.printing import vlatex, vpprint, vprint, vsprint

__all__ = ['linear_momentum', 'angular_momentum', 'kinetic_energy', 'potential_energy', 'Lagrangian', 'mechanics_printing', 'mprint', 'msprint', 'mpprint', 'mlatex', 'msubs', 'find_dynamicsymbols']

mprint = vprint
msprint = vsprint
mpprint = vpprint
mlatex = vlatex

def mechanics_printing(**kwargs) -> None: ...
def linear_momentum(frame, *body): ...
def angular_momentum(point, frame, *body): ...
def kinetic_energy(frame, *body): ...
def potential_energy(*body): ...
def Lagrangian(frame, *body): ...
def find_dynamicsymbols(expression, exclude: Incomplete | None = None, reference_frame: Incomplete | None = None): ...
def msubs(expr, *sub_dicts, smart: bool = False, **kwargs): ...
