from _typeshed import Incomplete
from sympy.physics.mechanics.method import _Methods

__all__ = ['JointsMethod']

class JointsMethod(_Methods):
    frame: Incomplete
    def __init__(self, newtonion, *joints) -> None: ...
    @property
    def bodies(self): ...
    @property
    def loads(self): ...
    @property
    def q(self): ...
    @property
    def u(self): ...
    @property
    def kdes(self): ...
    @property
    def forcing_full(self): ...
    @property
    def mass_matrix_full(self): ...
    @property
    def mass_matrix(self): ...
    @property
    def forcing(self): ...
    @property
    def method(self): ...
    def form_eoms(self, method=...): ...
    def rhs(self, inv_method: Incomplete | None = None): ...
