import abc
from _typeshed import Incomplete
from abc import ABC

__all__ = ['Joint', 'PinJoint', 'PrismaticJoint', 'CylindricalJoint', 'PlanarJoint', 'SphericalJoint', 'WeldJoint']

class Joint(ABC, metaclass=abc.ABCMeta):
    def __init__(self, name, parent, child, coordinates: Incomplete | None = None, speeds: Incomplete | None = None, parent_point: Incomplete | None = None, child_point: Incomplete | None = None, parent_interframe: Incomplete | None = None, child_interframe: Incomplete | None = None, parent_axis: Incomplete | None = None, child_axis: Incomplete | None = None, parent_joint_pos: Incomplete | None = None, child_joint_pos: Incomplete | None = None) -> None: ...
    @property
    def name(self): ...
    @property
    def parent(self): ...
    @property
    def child(self): ...
    @property
    def coordinates(self): ...
    @property
    def speeds(self): ...
    @property
    def kdes(self): ...
    @property
    def parent_axis(self): ...
    @property
    def child_axis(self): ...
    @property
    def parent_point(self): ...
    @property
    def child_point(self): ...
    @property
    def parent_interframe(self): ...
    @property
    def child_interframe(self): ...

class PinJoint(Joint):
    def __init__(self, name, parent, child, coordinates: Incomplete | None = None, speeds: Incomplete | None = None, parent_point: Incomplete | None = None, child_point: Incomplete | None = None, parent_interframe: Incomplete | None = None, child_interframe: Incomplete | None = None, parent_axis: Incomplete | None = None, child_axis: Incomplete | None = None, joint_axis: Incomplete | None = None, parent_joint_pos: Incomplete | None = None, child_joint_pos: Incomplete | None = None) -> None: ...
    @property
    def joint_axis(self): ...

class PrismaticJoint(Joint):
    def __init__(self, name, parent, child, coordinates: Incomplete | None = None, speeds: Incomplete | None = None, parent_point: Incomplete | None = None, child_point: Incomplete | None = None, parent_interframe: Incomplete | None = None, child_interframe: Incomplete | None = None, parent_axis: Incomplete | None = None, child_axis: Incomplete | None = None, joint_axis: Incomplete | None = None, parent_joint_pos: Incomplete | None = None, child_joint_pos: Incomplete | None = None) -> None: ...
    @property
    def joint_axis(self): ...

class CylindricalJoint(Joint):
    def __init__(self, name, parent, child, rotation_coordinate: Incomplete | None = None, translation_coordinate: Incomplete | None = None, rotation_speed: Incomplete | None = None, translation_speed: Incomplete | None = None, parent_point: Incomplete | None = None, child_point: Incomplete | None = None, parent_interframe: Incomplete | None = None, child_interframe: Incomplete | None = None, joint_axis: Incomplete | None = None) -> None: ...
    @property
    def joint_axis(self): ...
    @property
    def rotation_coordinate(self): ...
    @property
    def translation_coordinate(self): ...
    @property
    def rotation_speed(self): ...
    @property
    def translation_speed(self): ...

class PlanarJoint(Joint):
    def __init__(self, name, parent, child, rotation_coordinate: Incomplete | None = None, planar_coordinates: Incomplete | None = None, rotation_speed: Incomplete | None = None, planar_speeds: Incomplete | None = None, parent_point: Incomplete | None = None, child_point: Incomplete | None = None, parent_interframe: Incomplete | None = None, child_interframe: Incomplete | None = None) -> None: ...
    @property
    def rotation_coordinate(self): ...
    @property
    def planar_coordinates(self): ...
    @property
    def rotation_speed(self): ...
    @property
    def planar_speeds(self): ...
    @property
    def rotation_axis(self): ...
    @property
    def planar_vectors(self): ...

class SphericalJoint(Joint):
    def __init__(self, name, parent, child, coordinates: Incomplete | None = None, speeds: Incomplete | None = None, parent_point: Incomplete | None = None, child_point: Incomplete | None = None, parent_interframe: Incomplete | None = None, child_interframe: Incomplete | None = None, rot_type: str = 'BODY', amounts: Incomplete | None = None, rot_order: int = 123) -> None: ...

class WeldJoint(Joint):
    def __init__(self, name, parent, child, parent_point: Incomplete | None = None, child_point: Incomplete | None = None, parent_interframe: Incomplete | None = None, child_interframe: Incomplete | None = None) -> None: ...
