def multi_mass_spring_damper(n: int = 1, apply_gravity: bool = False, apply_external_forces: bool = False): ...
def n_link_pendulum_on_cart(n: int = 1, cart_force: bool = True, joint_torques: bool = False): ...
