from _typeshed import Incomplete
from sympy.physics.mechanics.body_base import BodyBase

__all__ = ['Particle']

class Particle(BodyBase):
    point: Incomplete
    def __init__(self, name, point: Incomplete | None = None, mass: Incomplete | None = None) -> None: ...
    def linear_momentum(self, frame): ...
    def angular_momentum(self, point, frame): ...
    def kinetic_energy(self, frame): ...
    potential_energy: Incomplete
    def set_potential_energy(self, scalar) -> None: ...
    def parallel_axis(self, point, frame): ...
