from _typeshed import Incomplete
from sympy.core import Basic as Basic

class EPath:
    def __new__(cls, path): ...
    def apply(self, expr, func, args: Incomplete | None = None, kwargs: Incomplete | None = None): ...
    def select(self, expr): ...

def epath(path, expr: Incomplete | None = None, func: Incomplete | None = None, args: Incomplete | None = None, kwargs: Incomplete | None = None): ...
