import numpy as np
from cvxpy.interface.numpy_interface.ndarray_interface import NDArrayInterface as NDArrayInterface

class MatrixInterface(NDArrayInterface):
    TARGET_MATRIX = np.matrix
    def const_to_matrix(self, value, convert_scalars: bool = False): ...
    def identity(self, size): ...
    def scalar_matrix(self, value, shape: tuple[int, ...]): ...
    def reshape(self, matrix, size): ...
