import numpy
from .. import base_matrix_interface as base
from _typeshed import Incomplete

COMPLEX_TYPES: Incomplete

class NDArrayInterface(base.BaseMatrixInterface):
    TARGET_MATRIX = numpy.ndarray
    def const_to_matrix(self, value, convert_scalars: bool = False): ...
    def identity(self, size): ...
    def shape(self, matrix) -> tuple[int, ...]: ...
    def size(self, matrix): ...
    def scalar_value(self, matrix): ...
    def scalar_matrix(self, value, shape: tuple[int, ...]): ...
    def reshape(self, matrix, size): ...
