from _typeshed import Incomplete
from cvxpy.interface.numpy_interface.ndarray_interface import NDArrayInterface as NDArrayInterface

class SparseMatrixInterface(NDArrayInterface):
    TARGET_MATRIX: Incomplete
    def const_to_matrix(self, value, convert_scalars: bool = False): ...
    def identity(self, size): ...
    def size(self, matrix): ...
    def scalar_value(self, matrix): ...
    def zeros(self, rows, cols): ...
    def reshape(self, matrix, size): ...
    def block_add(self, matrix, block, vert_offset, horiz_offset, rows, cols, vert_step: int = 1, horiz_step: int = 1) -> None: ...
