from _typeshed import Incomplete
from cvxpy.constraints import ExpCone as ExpCone, NonNeg as NonNeg, SOC as SOC, Zero as Zero
from cvxpy.reductions.solution import Solution as Solution, failure_solution as failure_solution
from cvxpy.reductions.solvers import utilities as utilities
from cvxpy.reductions.solvers.conic_solvers.conic_solver import ConicSolver as ConicSolver

def dims_to_solver_dict(cone_dims): ...

class ECOS(ConicSolver):
    MIP_CAPABLE: bool
    SUPPORTED_CONSTRAINTS: Incomplete
    STATUS_MAP: Incomplete
    EXP_CONE_ORDER: Incomplete
    def import_solver(self) -> None: ...
    def name(self): ...
    def apply(self, problem): ...
    def solve_via_data(self, data, warm_start: bool, verbose: bool, solver_opts, solver_cache: Incomplete | None = None): ...
    def invert(self, solution, inverse_data): ...
