from _typeshed import Incomplete
from cvxpy.reductions.solvers.conic_solvers.conic_solver import ConicSolver as ConicSolver
from cvxpy.reductions.solvers.conic_solvers.cvxopt_conif import CVXOPT as CVXOPT

class GLPK(CVXOPT):
    MIP_CAPABLE: bool
    SUPPORTED_CONSTRAINTS: Incomplete
    MIN_CONSTRAINT_LENGTH: int
    def name(self): ...
    def import_solver(self) -> None: ...
    def invert(self, solution, inverse_data): ...
    def solve_via_data(self, data, warm_start: bool, verbose: bool, solver_opts, solver_cache: Incomplete | None = None): ...
