import numpy as np
from _typeshed import Incomplete
from cvxpy.constraints import ExpCone as ExpCone, PSD as PSD, PowCone3D as PowCone3D, SOC as SOC
from cvxpy.expressions.expression import Expression as Expression
from cvxpy.reductions.solution import Solution as Solution, failure_solution as failure_solution
from cvxpy.reductions.solvers import utilities as utilities
from cvxpy.reductions.solvers.conic_solvers.conic_solver import ConicSolver as ConicSolver
from cvxpy.utilities.versioning import Version as Version

def dims_to_solver_dict(cone_dims): ...
def tri_to_full(lower_tri, n): ...
def scs_psdvec_to_psdmat(vec: Expression, indices: np.ndarray) -> Expression: ...

class SCS(ConicSolver):
    MIP_CAPABLE: bool
    SUPPORTED_CONSTRAINTS: Incomplete
    REQUIRES_CONSTR: bool
    STATUS_MAP: Incomplete
    EXP_CONE_ORDER: Incomplete
    ACCELERATION_RETRY_MESSAGE: str
    def name(self): ...
    def import_solver(self) -> None: ...
    def supports_quad_obj(self) -> bool: ...
    @staticmethod
    def psd_format_mat(constr): ...
    def apply(self, problem): ...
    @staticmethod
    def extract_dual_value(result_vec, offset, constraint): ...
    def invert(self, solution, inverse_data): ...
    @staticmethod
    def parse_solver_options(solver_opts): ...
    def solve_via_data(self, data, warm_start: bool, verbose: bool, solver_opts, solver_cache: Incomplete | None = None): ...
