from _typeshed import Incomplete
from cvxpy.constraints import NonNeg as NonNeg, PSD as PSD, Zero as Zero
from cvxpy.reductions.solution import Solution as Solution, failure_solution as failure_solution
from cvxpy.reductions.solvers import utilities as utilities
from cvxpy.reductions.solvers.conic_solvers.conic_solver import ConicSolver as ConicSolver
from cvxpy.reductions.solvers.solver import Solver as Solver

def dims_to_solver_dict(cone_dims): ...

class SDPA(ConicSolver):
    MIP_CAPABLE: bool
    SUPPORTED_CONSTRAINTS: Incomplete
    STATUS_MAP: Incomplete
    def name(self): ...
    def import_solver(self) -> None: ...
    def accepts(self, problem) -> bool: ...
    def apply(self, problem): ...
    def invert(self, solution, inverse_data): ...
    def solve_via_data(self, data, warm_start: bool, verbose: bool, solver_opts, solver_cache: Incomplete | None = None): ...
