from _typeshed import Incomplete
from cvxpy.constraints import Equality as Equality, Inequality as Inequality, NonNeg as NonNeg, NonPos as NonPos, Zero as Zero
from cvxpy.reductions.canonicalization import Canonicalization as Canonicalization
from cvxpy.reductions.cvx_attr2constr import convex_attributes as convex_attributes
from cvxpy.reductions.utilities import are_args_affine as are_args_affine

def accepts(problem): ...

class Qp2SymbolicQp(Canonicalization):
    def __init__(self, problem: Incomplete | None = None) -> None: ...
    def accepts(self, problem): ...
    def apply(self, problem): ...
