from _typeshed import Incomplete

__all__ = ['field_isomorphism', 'primitive_element', 'to_number_field']

def field_isomorphism(a, b, *, fast: bool = True): ...
def primitive_element(extension, x: Incomplete | None = None, *, ex: bool = False, polys: bool = False): ...
def to_number_field(extension, theta: Incomplete | None = None, *, gen: Incomplete | None = None, alias: Incomplete | None = None): ...
