from cvxpy.lin_ops.tree_mat import mul as mul, sum_dicts as sum_dicts, tmul as tmul

def get_mul_funcs(sym_data): ...
def constr_unpack(constraints, vector): ...
def vec_to_dict(vector, var_offsets, var_sizes): ...
def dict_to_vec(val_dict, var_offsets, var_sizes, vec_len): ...
def constr_mul(constraints, var_dict, vec_size, is_abs): ...
def constr_tmul(constraints, values, is_abs): ...
