from _typeshed import Incomplete

__all__ = ['bernoulli_poly', 'bernoulli_c_poly', 'genocchi_poly', 'euler_poly', 'andre_poly']

def bernoulli_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def bernoulli_c_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def genocchi_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def euler_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def andre_poly(n, x: Incomplete | None = None, polys: bool = False): ...
