from sympy.core.symbol import Dummy as Dummy
from sympy.ntheory import nextprime as nextprime
from sympy.ntheory.modular import crt as crt
from sympy.polys.domains import PolynomialRing as PolynomialRing
from sympy.polys.galoistools import gf_div as gf_div, gf_from_dict as gf_from_dict, gf_gcd as gf_gcd, gf_gcdex as gf_gcdex, gf_lcm as gf_lcm
from sympy.polys.polyerrors import ModularGCDFailed as ModularGCDFailed

def modgcd_univariate(f, g): ...
def modgcd_bivariate(f, g): ...
def modgcd_multivariate(f, g): ...
def func_field_modgcd(f, g): ...
