from _typeshed import Incomplete

__all__ = ['jacobi_poly', 'chebyshevt_poly', 'chebyshevu_poly', 'hermite_poly', 'hermite_prob_poly', 'legendre_poly', 'laguerre_poly']

def jacobi_poly(n, a, b, x: Incomplete | None = None, polys: bool = False): ...
def chebyshevt_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def chebyshevu_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def hermite_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def hermite_prob_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def legendre_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def laguerre_poly(n, x: Incomplete | None = None, alpha: int = 0, polys: bool = False): ...
