from _typeshed import Incomplete

__all__ = ['apart', 'apart_list', 'assemble_partfrac_list']

def apart(f, x: Incomplete | None = None, full: bool = False, **options): ...
def apart_list(f, x: Incomplete | None = None, dummies: Incomplete | None = None, **options): ...
def assemble_partfrac_list(partial_list): ...
