from _typeshed import Incomplete
from collections.abc import Generator

def using(**kwargs) -> Generator[None]: ...
def setup(key, value: Incomplete | None = None) -> None: ...
def query(key): ...
def configure() -> None: ...
