from _typeshed import Incomplete

__all__ = ['symmetrize', 'horner', 'interpolate', 'rational_interpolate', 'viete']

def symmetrize(F, *gens, **args): ...
def horner(f, *gens, **args): ...
def interpolate(data, x): ...
def rational_interpolate(data, degnum, X=...): ...
def viete(f, roots: Incomplete | None = None, *gens, **args): ...
