from _typeshed import Incomplete

__all__ = ['swinnerton_dyer_poly', 'cyclotomic_poly', 'symmetric_poly', 'random_poly', 'interpolating_poly']

def swinnerton_dyer_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def cyclotomic_poly(n, x: Incomplete | None = None, polys: bool = False): ...
def symmetric_poly(n, *gens, polys: bool = False): ...
def random_poly(x, n, inf, sup, domain=..., polys: bool = False): ...
def interpolating_poly(n, x, X: str = 'x', Y: str = 'y'): ...
