from sympy.polys.densearith import dmp_mul as dmp_mul, dmp_mul_ground as dmp_mul_ground, dmp_neg as dmp_neg, dmp_quo as dmp_quo, dmp_sub as dmp_sub, dup_mul as dup_mul, dup_mul_ground as dup_mul_ground, dup_neg as dup_neg, dup_quo as dup_quo, dup_sub as dup_sub
from sympy.polys.densebasic import dmp_degree as dmp_degree, dmp_degree_in as dmp_degree_in, dmp_degree_list as dmp_degree_list, dmp_ground as dmp_ground, dmp_ground_LC as dmp_ground_LC, dmp_inject as dmp_inject, dmp_raise as dmp_raise, dmp_zero_p as dmp_zero_p, dup_LC as dup_LC, dup_convert as dup_convert, dup_degree as dup_degree, dup_strip as dup_strip
from sympy.polys.densetools import dmp_diff as dmp_diff, dmp_diff_in as dmp_diff_in, dmp_ground_monic as dmp_ground_monic, dmp_ground_primitive as dmp_ground_primitive, dmp_shift as dmp_shift, dup_diff as dup_diff, dup_monic as dup_monic, dup_primitive as dup_primitive, dup_shift as dup_shift
from sympy.polys.euclidtools import dmp_gcd as dmp_gcd, dmp_inner_gcd as dmp_inner_gcd, dmp_primitive as dmp_primitive, dmp_resultant as dmp_resultant, dup_gcd as dup_gcd, dup_inner_gcd as dup_inner_gcd
from sympy.polys.galoistools import gf_sqf_list as gf_sqf_list, gf_sqf_part as gf_sqf_part
from sympy.polys.polyerrors import DomainError as DomainError, MultivariatePolynomialError as MultivariatePolynomialError

def dup_sqf_p(f, K): ...
def dmp_sqf_p(f, u, K): ...
def dup_sqf_norm(f, K): ...
def dmp_sqf_norm(f, u, K): ...
def dmp_norm(f, u, K): ...
def dup_gf_sqf_part(f, K): ...
def dmp_gf_sqf_part(f, u, K) -> None: ...
def dup_sqf_part(f, K): ...
def dmp_sqf_part(f, u, K): ...
def dup_gf_sqf_list(f, K, all: bool = False): ...
def dmp_gf_sqf_list(f, u, K, all: bool = False) -> None: ...
def dup_sqf_list(f, K, all: bool = False): ...
def dup_sqf_list_include(f, K, all: bool = False): ...
def dmp_sqf_list(f, u, K, all: bool = False): ...
def dmp_sqf_list_include(f, u, K, all: bool = False): ...
def dup_gff_list(f, K): ...
def dmp_gff_list(f, u, K): ...
