from cvxpy.atoms.atom import Atom as Atom
from cvxpy.atoms.axis_atom import AxisAtom as AxisAtom

class cummax(AxisAtom):
    def __init__(self, x, axis: int = 0) -> None: ...
    def numeric(self, values): ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def get_data(self): ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
