import numpy as np
from cvxpy.atoms.affine.affine_atom import AffAtom as AffAtom
from cvxpy.atoms.axis_atom import AxisAtom as AxisAtom
from cvxpy.expressions.expression import Expression as Expression

class cumprod(AffAtom, AxisAtom):
    def __init__(self, expr: Expression, axis: int = 0) -> None: ...
    def numeric(self, values) -> np.ndarray: ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def get_data(self) -> list: ...
