from _typeshed import Incomplete
from cvxpy.atoms.atom import Atom as Atom

class dist_ratio(Atom):
    a: Incomplete
    b: Incomplete
    def __init__(self, x, a, b) -> None: ...
    def numeric(self, values): ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_atom_quasiconvex(self) -> bool: ...
    def is_atom_quasiconcave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
