from cvxpy.atoms.atom import Atom as Atom

def resolvent(X, s: float): ...

class eye_minus_inv(Atom):
    def __init__(self, X) -> None: ...
    def numeric(self, values): ...
    def name(self) -> str: ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
