from _typeshed import Incomplete
from cvxpy.atoms.atom import Atom as Atom
from cvxpy.expressions import cvxtypes as cvxtypes

class gmatmul(Atom):
    A: Incomplete
    def __init__(self, A, X) -> None: ...
    def numeric(self, values): ...
    def name(self) -> str: ...
    def validate_arguments(self) -> None: ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def get_data(self): ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def parameters(self): ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
