from _typeshed import Incomplete
from cvxpy.atoms.lambda_max import lambda_max as lambda_max
from cvxpy.atoms.sum_largest import sum_largest as sum_largest

class lambda_sum_largest(lambda_max):
    k: Incomplete
    def __init__(self, X, k) -> None: ...
    def validate_arguments(self) -> None: ...
    def numeric(self, values): ...
    def get_data(self): ...
    @property
    def value(self): ...
