from _typeshed import Incomplete
from cvxpy.atoms.atom import Atom as Atom
from cvxpy.atoms.axis_atom import AxisAtom as AxisAtom

class log_sum_exp(AxisAtom):
    def __init__(self, x, axis: Incomplete | None = None, keepdims: bool = False) -> None: ...
    def numeric(self, values): ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
