from cvxpy.atoms.atom import Atom as Atom
from cvxpy.atoms.quad_form import QuadForm as QuadForm
from cvxpy.constraints.constraint import Constraint as Constraint

class MatrixFrac(Atom):
    def __init__(self, X, P) -> None: ...
    def numeric(self, values): ...
    def validate_arguments(self) -> None: ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def is_quadratic(self) -> bool: ...
    def has_quadratic_term(self) -> bool: ...
    def is_qpwa(self) -> bool: ...

def matrix_frac(X, P): ...
