from cvxpy.atoms.atom import Atom as Atom
from cvxpy.atoms.axis_atom import AxisAtom as AxisAtom
from cvxpy.expressions import cvxtypes as cvxtypes

class min(AxisAtom):
    __EXPR_AXIS_ERROR__: str
    def __init__(self, x, axis: int | None = None, keepdims: bool = False) -> None: ...
    def numeric(self, values): ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def is_pwl(self) -> bool: ...
