from cvxpy.atoms.axis_atom import AxisAtom as AxisAtom
from cvxpy.constraints.constraint import Constraint as Constraint

class norm1(AxisAtom):
    def numeric(self, values): ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def is_pwl(self) -> bool: ...
    def get_data(self): ...
    def name(self) -> str: ...
