from cvxpy.atoms.affine.binary_operators import multiply as multiply
from cvxpy.atoms.atom import Atom as Atom

def diff_pos(x, y): ...

class one_minus_pos(Atom):
    def __init__(self, x) -> None: ...
    def numeric(self, values): ...
    def name(self) -> str: ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
