from _typeshed import Incomplete
from cvxpy.atoms.affine.hstack import hstack as hstack
from cvxpy.atoms.axis_atom import AxisAtom as AxisAtom

class Prod(AxisAtom):
    def __init__(self, expr, axis: Incomplete | None = None, keepdims: bool = False) -> None: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def numeric(self, values): ...

def prod(expr, axis: Incomplete | None = None, keepdims: bool = False) -> Prod: ...
