from _typeshed import Incomplete
from cvxpy.atoms.norm import norm as norm
from cvxpy.atoms.sum_squares import sum_squares as sum_squares

def mean(x, axis: Incomplete | None = None, keepdims: bool = False): ...
def std(x, axis: Incomplete | None = None, keepdims: bool = False, ddof: int = 0): ...
def var(x, axis: Incomplete | None = None, keepdims: bool = False, ddof: int = 0): ...
