from _typeshed import Incomplete
from cvxpy import settings as settings
from cvxpy.expressions.expression import Expression as Expression
from cvxpy.reductions.canonicalization import Canonicalization as Canonicalization
from cvxpy.reductions.dgp2dcp.canonicalizers import DgpCanonMethods as DgpCanonMethods

class Dgp2Dcp(Canonicalization):
    def __init__(self, problem: Incomplete | None = None) -> None: ...
    def accepts(self, problem): ...
    canon_methods: Incomplete
    def apply(self, problem): ...
    def canonicalize_expr(self, expr: Expression, args: list, canonicalize_params: bool = True): ...
    def invert(self, solution, inverse_data): ...
