from _typeshed import Incomplete
from collections.abc import Generator

def identity(x) -> Generator[Incomplete]: ...
def exhaust(brule): ...
def onaction(brule, fn): ...
def debug(brule, file: Incomplete | None = None): ...
def multiplex(*brules): ...
def condition(cond, brule): ...
def sfilter(pred, brule): ...
def notempty(brule): ...
def do_one(*brules): ...
def chain(*brules): ...
def yieldify(rl): ...
