__all__ = ['pole_zero_numerical_data', 'pole_zero_plot', 'step_response_numerical_data', 'step_response_plot', 'impulse_response_numerical_data', 'impulse_response_plot', 'ramp_response_numerical_data', 'ramp_response_plot', 'bode_magnitude_numerical_data', 'bode_phase_numerical_data', 'bode_magnitude_plot', 'bode_phase_plot', 'bode_plot']

np = numpy

def pole_zero_numerical_data(system): ...
def pole_zero_plot(system, pole_color: str = 'blue', pole_markersize: int = 10, zero_color: str = 'orange', zero_markersize: int = 7, grid: bool = True, show_axes: bool = True, show: bool = True, **kwargs): ...
def step_response_numerical_data(system, prec: int = 8, lower_limit: int = 0, upper_limit: int = 10, **kwargs): ...
def step_response_plot(system, color: str = 'b', prec: int = 8, lower_limit: int = 0, upper_limit: int = 10, show_axes: bool = False, grid: bool = True, show: bool = True, **kwargs): ...
def impulse_response_numerical_data(system, prec: int = 8, lower_limit: int = 0, upper_limit: int = 10, **kwargs): ...
def impulse_response_plot(system, color: str = 'b', prec: int = 8, lower_limit: int = 0, upper_limit: int = 10, show_axes: bool = False, grid: bool = True, show: bool = True, **kwargs): ...
def ramp_response_numerical_data(system, slope: int = 1, prec: int = 8, lower_limit: int = 0, upper_limit: int = 10, **kwargs): ...
def ramp_response_plot(system, slope: int = 1, color: str = 'b', prec: int = 8, lower_limit: int = 0, upper_limit: int = 10, show_axes: bool = False, grid: bool = True, show: bool = True, **kwargs): ...
def bode_magnitude_numerical_data(system, initial_exp: int = -5, final_exp: int = 5, freq_unit: str = 'rad/sec', **kwargs): ...
def bode_magnitude_plot(system, initial_exp: int = -5, final_exp: int = 5, color: str = 'b', show_axes: bool = False, grid: bool = True, show: bool = True, freq_unit: str = 'rad/sec', **kwargs): ...
def bode_phase_numerical_data(system, initial_exp: int = -5, final_exp: int = 5, freq_unit: str = 'rad/sec', phase_unit: str = 'rad', phase_unwrap: bool = True, **kwargs): ...
def bode_phase_plot(system, initial_exp: int = -5, final_exp: int = 5, color: str = 'b', show_axes: bool = False, grid: bool = True, show: bool = True, freq_unit: str = 'rad/sec', phase_unit: str = 'rad', phase_unwrap: bool = True, **kwargs): ...
def bode_plot(system, initial_exp: int = -5, final_exp: int = 5, grid: bool = True, show_axes: bool = False, show: bool = True, freq_unit: str = 'rad/sec', phase_unit: str = 'rad', phase_unwrap: bool = True, **kwargs): ...
