from sympy.core.expr import Expr as Expr
from sympy.core.mul import Mul as Mul
from sympy.core.parameters import global_parameters as global_parameters
from sympy.core.singleton import S as S
from sympy.core.sympify import sympify as sympify

class TensorProduct(Expr):
    is_number: bool
    def __new__(cls, *args, **kwargs): ...
    def rank(self): ...
    @property
    def shape(self): ...
    def __getitem__(self, index): ...

def shape(expr): ...

class NoShapeError(Exception): ...
