import abc
from cvxpy.atoms.atom import Atom as Atom

class Elementwise(Atom, metaclass=abc.ABCMeta):
    def shape_from_args(self) -> tuple[int, ...]: ...
    def validate_arguments(self) -> None: ...
    def is_symmetric(self) -> bool: ...
    @staticmethod
    def elemwise_grad_to_diag(value, rows, cols): ...
