from cvxpy.atoms.elementwise.elementwise import Elementwise as Elementwise
from cvxpy.constraints.constraint import Constraint as Constraint

class entr(Elementwise):
    def __init__(self, x) -> None: ...
    def numeric(self, values): ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
