from _typeshed import Incomplete
from cvxpy.atoms.elementwise.elementwise import Elementwise as Elementwise

class huber(Elementwise):
    M: Incomplete
    def __init__(self, x, M: int = 1) -> None: ...
    def parameters(self): ...
    def numeric(self, values) -> float: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def is_quadratic(self) -> bool: ...
    def has_quadratic_term(self) -> bool: ...
    def get_data(self): ...
    def validate_arguments(self) -> None: ...
