from cvxpy.atoms.elementwise.log import log as log
from cvxpy.constraints.constraint import Constraint as Constraint

class log1p(log):
    def __init__(self, x) -> None: ...
    def numeric(self, values): ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
