from .printing import init_vprinting as init_vprinting, vlatex as vlatex, vpprint as vpprint, vprint as vprint, vsprint as vsprint
from _typeshed import Incomplete

__all__ = ['cross', 'dot', 'express', 'time_derivative', 'outer', 'kinematic_equations', 'get_motion_params', 'partial_velocity', 'dynamicsymbols', 'vprint', 'vsprint', 'vpprint', 'vlatex', 'init_vprinting']

def cross(vec1, vec2): ...
def dot(vec1, vec2): ...
def express(expr, frame, frame2: Incomplete | None = None, variables: bool = False): ...
def time_derivative(expr, frame, order: int = 1): ...
def outer(vec1, vec2): ...
def kinematic_equations(speeds, coords, rot_type, rot_order: str = ''): ...
def get_motion_params(frame, **kwargs): ...
def partial_velocity(vel_vecs, gen_speeds, frame): ...
def dynamicsymbols(names, level: int = 0, **assumptions): ...
