from _typeshed import Incomplete
from cvxpy.constraints.constraint import Constraint as Constraint
from cvxpy.expressions import cvxtypes as cvxtypes
from cvxpy.utilities import scopes as scopes

class FiniteSet(Constraint):
    expre: Incomplete
    vec: Incomplete
    def __init__(self, expre, vec, ineq_form: bool = False, constr_id: Incomplete | None = None) -> None: ...
    def name(self) -> str: ...
    def get_data(self): ...
    def is_dcp(self, dpp: bool = False) -> bool: ...
    def is_dgp(self, dpp: bool = False) -> bool: ...
    def is_dqcp(self) -> bool: ...
    @property
    def size(self): ...
    @property
    def ineq_form(self) -> bool: ...
    @property
    def shape(self): ...
    @property
    def residual(self): ...
