from _typeshed import Incomplete
from cvxpy.constraints.cones import Cone as Cone
from cvxpy.expressions import cvxtypes as cvxtypes
from cvxpy.utilities import scopes as scopes

class PowCone3D(Cone):
    x: Incomplete
    y: Incomplete
    z: Incomplete
    alpha: Incomplete
    def __init__(self, x, y, z, alpha, constr_id: Incomplete | None = None) -> None: ...
    @property
    def residual(self): ...
    def get_data(self): ...
    def is_imag(self) -> bool: ...
    def is_complex(self) -> bool: ...
    @property
    def size(self) -> int: ...
    def num_cones(self): ...
    def cone_sizes(self) -> list[int]: ...
    def is_dcp(self, dpp: bool = False) -> bool: ...
    def is_dgp(self, dpp: bool = False) -> bool: ...
    def is_dqcp(self) -> bool: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def save_dual_value(self, value) -> None: ...

class PowConeND(Cone):
    W: Incomplete
    z: Incomplete
    alpha: Incomplete
    axis: Incomplete
    def __init__(self, W, z, alpha, axis: int = 0, constr_id: Incomplete | None = None) -> None: ...
    def is_imag(self) -> bool: ...
    def is_complex(self) -> bool: ...
    def get_data(self): ...
    @property
    def residual(self): ...
    def num_cones(self): ...
    @property
    def size(self) -> int: ...
    def cone_sizes(self) -> list[int]: ...
    def is_dcp(self, dpp: bool = False) -> bool: ...
    def is_dgp(self, dpp: bool = False) -> bool: ...
    def is_dqcp(self) -> bool: ...
    def save_dual_value(self, value) -> None: ...
