import numpy as np
from typing import Any

def stack_vals(variables: list, default: float, order: str = 'F') -> np.ndarray: ...
def expcone_permutor(n_cones, exp_cone_order) -> np.ndarray: ...
def extract_dual_value(result_vec, offset, constraint): ...
def get_dual_values(result_vec, parse_func, constraints) -> dict[Any, Any]: ...
