def orth(V, tol: float = 1e-12): ...
def onb_for_orthogonal_complement(V): ...
def is_diagonal(A): ...
def is_psd_within_tol(A, tol): ...
def gershgorin_psd_check(A, tol): ...

class SparseCholeskyMessages:
    ASYMMETRIC: str
    INDEFINITE: str
    EIGEN_FAIL: str
    NOT_SPARSE: str
    NOT_REAL: str

def sparse_cholesky(A, sym_tol=..., assume_posdef: bool = False): ...
