from cvxpy.atoms.quad_form import QuadForm as QuadForm, SymbolicQuadForm as SymbolicQuadForm
from cvxpy.expressions.variable import Variable as Variable

def replace_quad_forms(expr, quad_forms): ...
def replace_quad_form(expr, idx, quad_forms): ...
def restore_quad_forms(expr, quad_forms) -> None: ...
