def squeezed(shape: tuple[int, ...]) -> tuple[int, ...]: ...
def sum_shapes(shapes: list[tuple[int, ...]]) -> tuple[int, ...]: ...
def mul_shapes_promote(lh_shape: tuple[int, ...], rh_shape: tuple[int, ...]) -> tuple[tuple[int, ...], tuple[int, ...], tuple[int, ...]]: ...
def mul_shapes(lh_shape: tuple[int, ...], rh_shape: tuple[int, ...]) -> tuple[int, ...]: ...
def size_from_shape(shape) -> int: ...
