from .exceptions import DMDomainError as DMDomainError, DMNonInvertibleMatrixError as DMNonInvertibleMatrixError, DMNonSquareMatrixError as DMNonSquareMatrixError, DMShapeError as DMShapeError
from sympy.polys.matrices._typing import RingElement as RingElement
from typing import Sequence, TypeVar

T = TypeVar('T')
R = TypeVar('R', bound=RingElement)

def ddm_transpose(matrix: Sequence[Sequence[T]]) -> list[list[T]]: ...
def ddm_iadd(a: list[list[R]], b: Sequence[Sequence[R]]) -> None: ...
def ddm_isub(a: list[list[R]], b: Sequence[Sequence[R]]) -> None: ...
def ddm_ineg(a: list[list[R]]) -> None: ...
def ddm_imul(a: list[list[R]], b: R) -> None: ...
def ddm_irmul(a: list[list[R]], b: R) -> None: ...
def ddm_imatmul(a: list[list[R]], b: Sequence[Sequence[R]], c: Sequence[Sequence[R]]) -> None: ...
def ddm_irref(a, _partial_pivot: bool = False): ...
def ddm_irref_den(a, K): ...
def ddm_idet(a, K): ...
def ddm_iinv(ainv, a, K) -> None: ...
def ddm_ilu_split(L, U, K): ...
def ddm_ilu(a): ...
def ddm_ilu_solve(x, L, U, swaps, b) -> None: ...
def ddm_berk(M, K): ...
