__all__ = ['DMError', 'DMBadInputError', 'DMDomainError', 'DMFormatError', 'DMRankError', 'DMShapeError', 'DMNotAField', 'DMNonInvertibleMatrixError', 'DMNonSquareMatrixError', 'DMValueError']

class DMError(Exception): ...
class DMBadInputError(DMError): ...
class DMDomainError(DMError): ...
class DMNotAField(DMDomainError): ...
class DMFormatError(DMError): ...
class DMNonInvertibleMatrixError(DMError): ...
class DMRankError(DMError): ...
class DMShapeError(DMError): ...
class DMNonSquareMatrixError(DMShapeError): ...
class DMValueError(DMError): ...
