from sympy.core.cache import cacheit as cacheit
from sympy.core.expr import Expr as Expr
from sympy.core.intfunc import igcdex as igcdex
from sympy.core.numbers import Integer as Integer
from sympy.core.singleton import S as S
from sympy.functions.elementary.miscellaneous import sqrt as sqrt
from typing import Callable

def migcdex(*x: int) -> tuple[tuple[int, ...], int]: ...
def ipartfrac(*denoms: int) -> tuple[int, ...]: ...
def fermat_coords(n: int) -> list[int] | None: ...
def cos_3() -> Expr: ...
def cos_5() -> Expr: ...
def cos_17() -> Expr: ...
def cos_257() -> Expr: ...
def cos_table() -> dict[int, Callable[[], Expr]]: ...
