from .utils import groupby as groupby

class AmbiguityWarning(Warning): ...

def supercedes(a, b): ...
def consistent(a, b): ...
def ambiguous(a, b): ...
def ambiguities(signatures): ...
def super_signature(signatures): ...
def edge(a, b, tie_breaker=...): ...
def ordering(signatures): ...
