from _typeshed import Incomplete
from sympy.core.numbers import I as I
from sympy.utilities.decorator import deprecated as deprecated

def msigma(i): ...
def pat_matrix(m, dx, dy, dz): ...
def mgamma(mu, lower: bool = False): ...

minkowski_tensor: Incomplete

def mdft(n): ...
