from sympy.core.symbol import Symbol

__all__ = ['evaluate_pauli_product']

class Pauli(Symbol):
    def __new__(cls, i, label: str = 'sigma'): ...
    def __getnewargs_ex__(self): ...
    def __mul__(self, other): ...

def evaluate_pauli_product(arg): ...
