from _typeshed import Incomplete
from cvxpy.lin_ops.canon_backend import CanonBackend as CanonBackend

def get_parameter_vector(param_size, param_id_to_col, param_id_to_size, param_id_to_value_fn, zero_offset: bool = False): ...
def reduce_problem_data_tensor(A, var_length, quad_form: bool = False): ...
def nonzero_csc_matrix(A): ...
def A_mapping_nonzero_rows(problem_data_tensor, var_length): ...
def get_matrix_from_tensor(problem_data_tensor, param_vec, var_length, nonzero_rows: Incomplete | None = None, with_offset: bool = True, problem_data_index: Incomplete | None = None): ...
def get_default_canon_backend() -> str: ...
def get_problem_matrix(linOps, var_length, id_to_col, param_to_size, param_to_col, constr_length, canon_backend: str | None = None): ...
