from sympy.physics.quantum import Bra, Ket, Operator

__all__ = ['FermionOp', 'FermionFockKet', 'FermionFockBra']

class FermionOp(Operator):
    @property
    def name(self): ...
    @property
    def is_annihilation(self): ...
    @classmethod
    def default_args(self): ...
    def __new__(cls, *args, **hints): ...

class FermionFockKet(Ket):
    def __new__(cls, n): ...
    @property
    def n(self): ...
    @classmethod
    def dual_class(self): ...

class FermionFockBra(Bra):
    def __new__(cls, n): ...
    @property
    def n(self): ...
    @classmethod
    def dual_class(self): ...
