__all__ = ['numpy_ndarray', 'scipy_sparse_matrix', 'sympy_to_numpy', 'sympy_to_scipy_sparse', 'numpy_to_sympy', 'scipy_sparse_to_sympy', 'flatten_scalar', 'matrix_dagger', 'to_sympy', 'to_numpy', 'to_scipy_sparse', 'matrix_tensor_product', 'matrix_zeros']

class numpy_ndarray: ...
class scipy_sparse_matrix: ...

def sympy_to_numpy(m, **options): ...
def sympy_to_scipy_sparse(m, **options): ...
def scipy_sparse_to_sympy(m, **options): ...
def numpy_to_sympy(m, **options): ...
def to_sympy(m, **options): ...
def to_numpy(m, **options): ...
def to_scipy_sparse(m, **options): ...
def flatten_scalar(e): ...
def matrix_dagger(e): ...
def matrix_tensor_product(*product): ...
def matrix_zeros(m, n, **options): ...
