from sympy.core.expr import Expr

__all__ = ['QuantumError', 'QExpr']

class QuantumError(Exception): ...

class QExpr(Expr):
    is_commutative: bool
    @property
    def free_symbols(self): ...
    def __new__(cls, *args, **kwargs): ...
    @property
    def label(self): ...
    @property
    def is_symbolic(self): ...
    @classmethod
    def default_args(self) -> None: ...
