from sympy.physics.quantum.gate import Gate, OneQubitGate

__all__ = ['QFT', 'IQFT', 'RkGate', 'Rk']

class RkGate(OneQubitGate):
    gate_name: str
    gate_name_latex: str
    def __new__(cls, *args): ...
    @property
    def k(self): ...
    @property
    def targets(self): ...
    @property
    def gate_name_plot(self): ...
    def get_target_matrix(self, format: str = 'sympy'): ...
Rk = RkGate

class Fourier(Gate):
    @property
    def targets(self): ...
    @property
    def min_qubits(self): ...
    @property
    def size(self): ...
    @property
    def omega(self): ...

class QFT(Fourier):
    gate_name: str
    gate_name_latex: str
    def decompose(self): ...
    @property
    def omega(self): ...

class IQFT(Fourier):
    gate_name: str
    gate_name_latex: str
    def decompose(self): ...
    @property
    def omega(self): ...
