from _typeshed import Incomplete

__all__ = ['represent', 'rep_innerproduct', 'rep_expectation', 'integrate_result', 'get_basis', 'enumerate_states']

def represent(expr, **options): ...
def rep_innerproduct(expr, **options): ...
def rep_expectation(expr, **options): ...
def integrate_result(orig_expr, result, **options): ...
def get_basis(expr, *, basis: Incomplete | None = None, replace_none: bool = True, **options): ...
def enumerate_states(*args, **options): ...
