from sympy.core.expr import Expr

__all__ = ['TensorProduct', 'tensor_product_simp']

class TensorProduct(Expr):
    is_commutative: bool
    def __new__(cls, *args): ...
    @classmethod
    def flatten(cls, args): ...
    def doit(self, **hints): ...

def tensor_product_simp(e, **hints): ...
