from _typeshed import Incomplete
from cvxpy.problems.objective import Maximize as Maximize, Minimize as Minimize
from cvxpy.transforms import indicator as indicator

def weighted_sum(objectives: list[Minimize | Maximize], weights) -> Minimize | Maximize: ...
def targets_and_priorities(objectives: list[Minimize | Maximize], priorities, targets, limits: Incomplete | None = None, off_target: float = 1e-05) -> Minimize | Maximize: ...
def max(objectives: list[Minimize | Maximize], weights) -> Minimize: ...
def log_sum_exp(objectives: list[Minimize | Maximize], weights, gamma: float = 1.0) -> Minimize: ...
