from _typeshed import Incomplete
from cvxpy.atoms.suppfunc import SuppFuncAtom as SuppFuncAtom
from cvxpy.expressions.variable import Variable as Variable
from cvxpy.reductions.cvx_attr2constr import CONVEX_ATTRIBUTES as CONVEX_ATTRIBUTES

def scs_coniclift(x, constraints): ...
def scs_cone_selectors(K): ...

class SuppFunc:
    x: Incomplete
    constraints: Incomplete
    def __init__(self, x, constraints) -> None: ...
    def __call__(self, y) -> SuppFuncAtom: ...
    def conic_repr_of_set(self): ...
