from cvxpy.expressions.leaf import Leaf as Leaf

NESTED_LIST_WARNING: str

class Constant(Leaf):
    def __init__(self, value, name: str | None = None) -> None: ...
    def name(self) -> str: ...
    def constants(self) -> list['Constant']: ...
    def is_constant(self) -> bool: ...
    @property
    def value(self): ...
    def is_pos(self) -> bool: ...
    @property
    def grad(self): ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def canonicalize(self): ...
    def is_nonneg(self) -> bool: ...
    def is_nonpos(self) -> bool: ...
    def is_imag(self) -> bool: ...
    def is_complex(self) -> bool: ...
    def is_symmetric(self) -> bool: ...
    def is_hermitian(self) -> bool: ...
    def is_skew_symmetric(self) -> bool: ...
    def is_psd(self) -> bool: ...
    def is_nsd(self) -> bool: ...
