from _typeshed import Incomplete
from sympy.utilities.decorator import doctest_depends_on as doctest_depends_on

__doctest_requires__: Incomplete

def add_mathml_headers(s): ...
def apply_xsl(mml, xsl): ...
def c2p(mml, simple: bool = False): ...
