from sympy.core.logic import fuzzy_and as fuzzy_and, fuzzy_not as fuzzy_not, fuzzy_or as fuzzy_or, fuzzy_xor as fuzzy_xor

class intervalMembership:
    def __init__(self, a, b) -> None: ...
    def __getitem__(self, i): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __and__(self, other): ...
    def __or__(self, other): ...
    def __invert__(self): ...
    def __xor__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
