from sympy.external import import_module as import_module
from sympy.plotting.intervalmath import interval as interval

def Abs(x): ...
def exp(x): ...
def log(x): ...
def log10(x): ...
def atan(x): ...
def sin(x): ...
def cos(x): ...
def tan(x): ...
def sqrt(x): ...
def imin(*args): ...
def imax(*args): ...
def sinh(x): ...
def cosh(x): ...
def tanh(x): ...
def asin(x): ...
def acos(x): ...
def ceil(x): ...
def floor(x): ...
def acosh(x): ...
def asinh(x): ...
def atanh(x): ...
def And(*args): ...
def Or(*args): ...
