from _typeshed import Incomplete
from collections.abc import Generator
from sympy.core import Add as Add, Basic as Basic, Mul as Mul, Pow as Pow
from sympy.core.operations import AssocOp as AssocOp, LatticeOp as LatticeOp
from sympy.matrices import MatAdd as MatAdd, MatMul as MatMul, MatrixExpr as MatrixExpr
from sympy.sets.sets import FiniteSet as FiniteSet, Intersection as Intersection, Union as Union
from sympy.unify import core as core
from sympy.unify.core import Compound as Compound, CondVariable as CondVariable, Variable as Variable

basic_new_legal: Incomplete
eval_false_legal: Incomplete
illegal: Incomplete

def sympy_associative(op): ...
def sympy_commutative(op): ...
def is_associative(x): ...
def is_commutative(x): ...
def mk_matchtype(typ): ...
def deconstruct(s, variables=()): ...
def construct(t): ...
def rebuild(s): ...
def unify(x, y, s: Incomplete | None = None, variables=(), **kwargs) -> Generator[Incomplete, None, Incomplete]: ...
