from cvxpy.constraints.zero import Equality as Equality, Zero as Zero
from cvxpy.expressions.constants import Constant as Constant

def equality_canon(expr, real_args, imag_args, real2imag): ...
def zero_canon(expr, real_args, imag_args, real2imag): ...
