from sympy.core.containers import Tuple as Tuple
from sympy.core.singleton import S as S
from sympy.core.symbol import Symbol as Symbol
from sympy.core.sympify import SympifyError as SympifyError

class TableForm:
    def __init__(self, data, **kwarg) -> None: ...
    def as_matrix(self): ...
    def as_str(self): ...
    def as_latex(self): ...
