WARN: bool

def disable_warnings() -> None: ...
def enable_warnings() -> None: ...
def warnings_enabled() -> bool: ...

class SolverError(Exception): ...
class DCPError(Exception): ...
class DPPError(Exception): ...
class DGPError(Exception): ...
class DQCPError(Exception): ...
class ParameterError(Exception): ...
