from _typeshed import Incomplete

LOGGER: Incomplete
PLUS: str
MINUS: str
MUL: str
VAR_PREFIX: str
PARAM_PREFIX: str
NP_EQUAL_STR: str
EQ_CONSTR: str
INEQ_CONSTR: str
OPTIMAL: str
OPTIMAL_INACCURATE: str
INFEASIBLE: str
INFEASIBLE_INACCURATE: str
UNBOUNDED: str
UNBOUNDED_INACCURATE: str
INFEASIBLE_OR_UNBOUNDED: str
USER_LIMIT: str
SOLVER_ERROR: str
SOLUTION_PRESENT: Incomplete
INF_OR_UNB: Incomplete
INACCURATE: Incomplete
ERROR: Incomplete
CVXOPT: str
GLPK: str
GLPK_MI: str
GLOP: str
CBC: str
COPT: str
ECOS: str
ECOS_BB: str
SCS: str
SDPA: str
DIFFCP: str
GUROBI: str
OSQP: str
PIQP: str
PROXQP: str
CPLEX: str
MOSEK: str
XPRESS: str
NAG: str
PDLP: str
SCIP: str
SCIPY: str
CLARABEL: str
DAQP: str
HIGHS: str
SOLVERS: Incomplete
XPRESS_IIS: str
XPRESS_TROW: str
PARAM_PROB: str
PARALLEL: str
ROBUST_KKTSOLVER: str
EQ: Incomplete
LEQ: Incomplete
SOC: Incomplete
SOC_EW: Incomplete
PSD: Incomplete
EXP: Incomplete
BOOL: Incomplete
INT: Incomplete
EQ_DIM: str
LEQ_DIM: str
SOC_DIM: str
PSD_DIM: str
EXP_DIM: str
BOOL_IDS: str
BOOL_IDX: str
INT_IDS: str
INT_IDX: str
LOWER_BOUNDS: str
UPPER_BOUNDS: str
STATUS: str
VALUE: str
OBJ_OFFSET: str
PRIMAL: str
EQ_DUAL: str
INEQ_DUAL: str
SOLVE_TIME: str
SETUP_TIME: str
NUM_ITERS: str
EXTRA_STATS: str
C: str
OFFSET: str
P: str
Q: str
A: str
B: str
G: str
H: str
F: str
DIMS: str
CONSTANT: str
AFFINE: str
CONVEX: str
CONCAVE: str
QUASILINEAR: str
QUASICONVEX: str
QUASICONCAVE: str
LOG_LOG_CONSTANT: str
LOG_LOG_AFFINE: str
LOG_LOG_CONVEX: str
LOG_LOG_CONCAVE: str
ZERO: str
NONNEG: str
NONPOS: str
UNKNOWN: str
NUMPY_CANON_BACKEND: str
SCIPY_CANON_BACKEND: str
RUST_CANON_BACKEND: str
CPP_CANON_BACKEND: str
DEFAULT_CANON_BACKEND: Incomplete
EIGVAL_TOL: float
PSD_NSD_PROJECTION_TOL: float
GENERAL_PROJECTION_TOL: float
SPARSE_PROJECTION_TOL: float
ATOM_EVAL_TOL: float
CHOL_SYM_TOL: float
PARAM_THRESHOLD: float
NUM_THREADS: int
ALLOW_ND_EXPR: bool
PRINT_EDGEITEMS: int
PRINT_THRESHOLD: int

def set_num_threads(num_threads: int) -> None: ...
def get_num_threads() -> int: ...
