from _typeshed import Incomplete
from cvxpy.reductions.reduction import Reduction as Reduction

class Chain(Reduction):
    reductions: Incomplete
    def __init__(self, problem: Incomplete | None = None, reductions: Incomplete | None = None) -> None: ...
    def get(self, reduction_type): ...
    def accepts(self, problem) -> bool: ...
    def apply(self, problem, verbose: bool = False): ...
    def invert(self, solution, inverse_data): ...
