from cvxpy.expressions import cvxtypes as cvxtypes
from cvxpy.problems.objective import Maximize as Maximize, Minimize as Minimize
from cvxpy.reductions.reduction import Reduction as Reduction

class FlipObjective(Reduction):
    def accepts(self, problem) -> bool: ...
    def apply(self, problem): ...
    def invert(self, solution, inverse_data): ...
