import numpy as np
from cvxpy.reductions.reduction import Reduction as Reduction

def extract_lower_bounds(variables: list, var_size: int) -> np.ndarray | None: ...
def extract_upper_bounds(variables: list, var_size: int) -> np.ndarray | None: ...
def extract_mip_idx(variables) -> tuple[list[int], list[int]]: ...

class MatrixStuffing(Reduction):
    def apply(self, problem) -> None: ...
    def invert(self, solution, inverse_data) -> None: ...
    def stuffed_objective(self, problem, inverse_data) -> None: ...
