from .facts import FactKB as FactKB, FactRules as FactRules
from .sympify import sympify as sympify
from _typeshed import Incomplete
from sympy.utilities.exceptions import sympy_deprecation_warning as sympy_deprecation_warning

def assumptions(expr, _check: Incomplete | None = None): ...
def common_assumptions(exprs, check: Incomplete | None = None): ...
def failing_assumptions(expr, **assumptions): ...
def check_assumptions(expr, against: Incomplete | None = None, **assume): ...

class StdFactKB(FactKB):
    def __init__(self, facts: Incomplete | None = None) -> None: ...
    def copy(self): ...
    @property
    def generator(self): ...

def as_property(fact): ...
def make_property(fact): ...

class ManagedProperties(type):
    def __init__(cls, *args, **kwargs) -> None: ...
