from .sympify import SympifyError as SympifyError, sympify as sympify
from _typeshed import Incomplete

def call_highest_priority(method_name): ...
def sympify_method_args(cls): ...
def sympify_return(*args): ...

class _SympifyWrapper:
    func: Incomplete
    args: Incomplete
    def __init__(self, func, args) -> None: ...
    def make_wrapped(self, cls): ...
