import math
from .singleton import S as S
from .sympify import sympify as sympify
from sympy.external.gmpy import bit_scan1 as bit_scan1, gcdext as gcdext, iroot as iroot, sqrt as sqrt
from sympy.utilities.misc import as_int as as_int, filldedent as filldedent

def num_digits(n, base: int = 10): ...
def integer_log(n, b): ...
def trailing(n): ...
def igcd(*args): ...
igcd2 = math.gcd

def igcd_lehmer(a, b): ...
def ilcm(*args): ...
def igcdex(a, b): ...
def mod_inverse(a, m): ...
def isqrt(n): ...
def integer_nthroot(y, n): ...
