FuzzyBool = bool | None

def fuzzy_bool(x): ...
def fuzzy_and(args): ...
def fuzzy_not(v): ...
def fuzzy_or(args): ...
def fuzzy_xor(args): ...
def fuzzy_nand(args): ...

class Logic:
    op_2class: dict[str, type[Logic]]
    def __new__(cls, *args): ...
    def __getnewargs__(self): ...
    def __hash__(self): ...
    def __eq__(a, b): ...
    def __ne__(a, b): ...
    def __lt__(self, other): ...
    def __cmp__(self, other): ...
    @staticmethod
    def fromstring(text): ...

class AndOr_Base(Logic):
    def __new__(cls, *args): ...
    @classmethod
    def flatten(cls, args): ...

class And(AndOr_Base):
    op_x_notx: bool
    def expand(self): ...

class Or(AndOr_Base):
    op_x_notx: bool

class Not(Logic):
    def __new__(cls, arg): ...
    @property
    def arg(self): ...
