from _typeshed import Incomplete

def apply_on_element(f, args, kwargs, n): ...
def iter_copy(structure): ...
def structure_copy(structure): ...

class vectorize:
    mdargs: Incomplete
    def __init__(self, *mdargs) -> None: ...
    def __call__(self, f): ...
