from _typeshed import Incomplete

class Transform:
    def __init__(self, transform, filter=...) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __getitem__(self, key): ...
    def get(self, item, default: Incomplete | None = None): ...
