from _typeshed import Incomplete
from sympy.core.basic import Basic

__all__ = ['Medium']

class Medium(Basic):
    def __new__(cls, name, permittivity: Incomplete | None = None, permeability: Incomplete | None = None, n: Incomplete | None = None): ...
    @property
    def name(self): ...
    @property
    def speed(self): ...
    @property
    def refractive_index(self): ...

class MediumN(Medium):
    def __new__(cls, name, n): ...
    @property
    def n(self): ...

class MediumPP(Medium):
    def __new__(cls, name, permittivity, permeability): ...
    @property
    def intrinsic_impedance(self): ...
    @property
    def permittivity(self): ...
    @property
    def permeability(self): ...
    @property
    def n(self): ...
