from sympy.core.numbers import I as I, pi as pi
from sympy.functions.elementary.complexes import Abs as Abs, im as im, re as re
from sympy.functions.elementary.exponential import exp as exp
from sympy.functions.elementary.miscellaneous import sqrt as sqrt
from sympy.functions.elementary.trigonometric import cos as cos, sin as sin
from sympy.matrices.dense import Matrix as Matrix
from sympy.physics.quantum import TensorProduct as TensorProduct
from sympy.simplify.simplify import simplify as simplify

def jones_vector(psi, chi): ...
def stokes_vector(psi, chi, p: int = 1, I: int = 1): ...
def jones_2_stokes(e): ...
def linear_polarizer(theta: int = 0): ...
def phase_retarder(theta: int = 0, delta: int = 0): ...
def half_wave_retarder(theta): ...
def quarter_wave_retarder(theta): ...
def transmissive_filter(T): ...
def reflective_filter(R): ...
def mueller_matrix(J): ...
def polarizing_beam_splitter(Tp: int = 1, Rs: int = 1, Ts: int = 0, Rp: int = 0, phia: int = 0, phib: int = 0): ...
