from _typeshed import Incomplete

__all__ = ['refraction_angle', 'deviation', 'fresnel_coefficients', 'brewster_angle', 'critical_angle', 'lens_makers_formula', 'mirror_formula', 'lens_formula', 'hyperfocal_distance', 'transverse_magnification']

def refraction_angle(incident, medium1, medium2, normal: Incomplete | None = None, plane: Incomplete | None = None): ...
def fresnel_coefficients(angle_of_incidence, medium1, medium2): ...
def deviation(incident, medium1, medium2, normal: Incomplete | None = None, plane: Incomplete | None = None): ...
def brewster_angle(medium1, medium2): ...
def critical_angle(medium1, medium2): ...
def lens_makers_formula(n_lens, n_surr, r1, r2, d: int = 0): ...
def mirror_formula(focal_length: Incomplete | None = None, u: Incomplete | None = None, v: Incomplete | None = None): ...
def lens_formula(focal_length: Incomplete | None = None, u: Incomplete | None = None, v: Incomplete | None = None): ...
def hyperfocal_distance(f, N, c): ...
def transverse_magnification(si, so): ...
