from _typeshed import Incomplete
from sympy.core.expr import Expr

__all__ = ['TWave']

class TWave(Expr):
    def __new__(cls, amplitude, frequency: Incomplete | None = None, phase=..., time_period: Incomplete | None = None, n=...): ...
    @property
    def amplitude(self): ...
    @property
    def frequency(self): ...
    @property
    def phase(self): ...
    @property
    def time_period(self): ...
    @property
    def n(self): ...
    @property
    def wavelength(self): ...
    @property
    def speed(self): ...
    @property
    def angular_velocity(self): ...
    @property
    def wavenumber(self): ...
    def __add__(self, other): ...
    def __mul__(self, other): ...
    def __sub__(self, other): ...
    def __neg__(self): ...
    def __radd__(self, other): ...
    def __rmul__(self, other): ...
    def __rsub__(self, other): ...
