from _typeshed import Incomplete
from sympy.core import Atom as Atom, Basic as Basic

class CartanType_generator:
    def __call__(self, *args): ...

CartanType: Incomplete

class Standard_Cartan(Atom):
    def __new__(cls, series, n): ...
    def rank(self): ...
    def series(self): ...
