from .cartan_type import CartanType as CartanType
from sympy.core.basic import Atom as Atom

class RootSystem(Atom):
    def __new__(cls, cartantype): ...
    def simple_roots(self): ...
    def all_roots(self): ...
    def root_space(self): ...
    def add_simple_roots(self, root1, root2): ...
    def add_as_roots(self, root1, root2): ...
    def cartan_matrix(self): ...
    def dynkin_diagram(self): ...
