from .cartan_type import Standard_Cartan as Standard_Cartan
from sympy.core.backend import Matrix as Matrix

class TypeG(Standard_Cartan):
    def __new__(cls, n): ...
    def dimension(self): ...
    def simple_root(self, i): ...
    def positive_roots(self): ...
    def roots(self): ...
    def cartan_matrix(self): ...
    def basis(self): ...
    def dynkin_diagram(self): ...
