from .cartan_type import CartanType as CartanType
from sympy.core.backend import Matrix as Matrix, Rational as Rational, eye as eye, igcd as igcd
from sympy.core.basic import Atom as Atom

class WeylGroup(Atom):
    def __new__(cls, cartantype): ...
    def generators(self): ...
    def group_order(self): ...
    def group_name(self): ...
    def element_order(self, weylelt): ...
    def delete_doubles(self, reflections): ...
    def matrix_form(self, weylelt): ...
    def coxeter_diagram(self): ...
