from _typeshed import Incomplete
from cvxpy.reductions.solution import Solution as Solution, failure_solution as failure_solution
from cvxpy.reductions.solvers.conic_solvers.cplex_conif import get_status as get_status, hide_solver_output as hide_solver_output, set_parameters as set_parameters
from cvxpy.reductions.solvers.qp_solvers.qp_solver import QpSolver as QpSolver

def constrain_cplex_infty(v) -> None: ...

class CPLEX(QpSolver):
    MIP_CAPABLE: bool
    def name(self): ...
    def import_solver(self) -> None: ...
    def invert(self, results, inverse_data): ...
    def solve_via_data(self, data, warm_start: bool, verbose: bool, solver_opts, solver_cache: Incomplete | None = None): ...
