from _typeshed import Incomplete

__all__ = ['greek_unicode', 'sub', 'sup', 'xsym', 'vobj', 'hobj', 'pretty_symbol', 'annotated', 'center_pad', 'center']

greek_unicode: Incomplete
sub: Incomplete
sup: Incomplete

def vobj(symb, height): ...
def hobj(symb, width): ...
def xsym(sym): ...
def pretty_symbol(symb_name, bold_name: bool = False): ...
def annotated(letter): ...
def center_pad(wstring, wtarget, fillchar: str = ' '): ...
def center(string, width, fillchar: str = ' '): ...
