import abc
from cvxpy.atoms.atom import Atom as Atom
from cvxpy.cvxcore.python import canonInterface as canonInterface
from cvxpy.expressions.constants import Constant as Constant

class AffAtom(Atom, metaclass=abc.ABCMeta):
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_imag(self) -> bool: ...
    def is_complex(self) -> bool: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def is_quadratic(self) -> bool: ...
    def has_quadratic_term(self) -> bool: ...
    def is_qpwa(self) -> bool: ...
    def is_pwl(self) -> bool: ...
    def is_psd(self) -> bool: ...
    def is_nsd(self) -> bool: ...
