import cvxpy.lin_ops.lin_op as lo
from _typeshed import Incomplete
from cvxpy.atoms.affine.affine_atom import AffAtom as AffAtom
from cvxpy.constraints.constraint import Constraint as Constraint
from cvxpy.expressions.constants.parameter import is_param_free as is_param_free

class conv(AffAtom):
    def __init__(self, lh_expr, rh_expr) -> None: ...
    def numeric(self, values): ...
    def validate_arguments(self) -> None: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def shape_from_args(self) -> tuple[int, int]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def graph_implementation(self, arg_objs, shape: tuple[int, ...], data: Incomplete | None = None) -> tuple[lo.LinOp, list[Constraint]]: ...

class convolve(AffAtom):
    def numeric(self, values): ...
    def validate_arguments(self) -> None: ...
    def is_atom_convex(self) -> bool: ...
    def is_atom_concave(self) -> bool: ...
    def shape_from_args(self) -> tuple[int, int]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def graph_implementation(self, arg_objs, shape: tuple[int, ...], data: Incomplete | None = None) -> tuple[lo.LinOp, list[Constraint]]: ...
