import cvxpy.lin_ops.lin_op as lo
from _typeshed import Incomplete
from cvxpy.atoms.affine.affine_atom import AffAtom as AffAtom
from cvxpy.constraints.constraint import Constraint as Constraint
from cvxpy.expressions.expression import Expression as Expression

def promote(expr: Expression, shape: tuple[int, ...]): ...

class Promote(AffAtom):
    promoted_shape: Incomplete
    def __init__(self, expr, shape: tuple[int, ...]) -> None: ...
    def numeric(self, values): ...
    def is_symmetric(self) -> bool: ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def get_data(self): ...
    def graph_implementation(self, arg_objs, shape: tuple[int, ...], data: Incomplete | None = None) -> tuple[lo.LinOp, list[Constraint]]: ...
