import abc
import cvxpy.lin_ops.lin_op as lo
from _typeshed import Incomplete
from cvxpy.atoms.affine.affine_atom import AffAtom as AffAtom
from cvxpy.constraints.constraint import Constraint as Constraint

class UnaryOperator(AffAtom, metaclass=abc.ABCMeta):
    def __init__(self, expr) -> None: ...
    def name(self): ...
    def numeric(self, values): ...

class NegExpression(UnaryOperator):
    OP_NAME: str
    OP_FUNC: Incomplete
    def shape_from_args(self) -> tuple[int, ...]: ...
    def sign_from_args(self) -> tuple[bool, bool]: ...
    def is_incr(self, idx) -> bool: ...
    def is_decr(self, idx) -> bool: ...
    def is_symmetric(self) -> bool: ...
    def is_hermitian(self) -> bool: ...
    def graph_implementation(self, arg_objs, shape: tuple[int, ...], data: Incomplete | None = None) -> tuple[lo.LinOp, list[Constraint]]: ...
