import cvxpy.lin_ops.lin_op as lo
from _typeshed import Incomplete
from cvxpy.atoms.affine.affine_atom import AffAtom as AffAtom
from cvxpy.constraints.constraint import Constraint as Constraint

class Wrap(AffAtom):
    def __init__(self, arg) -> None: ...
    def is_atom_log_log_convex(self) -> bool: ...
    def is_atom_log_log_concave(self) -> bool: ...
    def numeric(self, values): ...
    def is_complex(self) -> bool: ...
    def shape_from_args(self) -> tuple[int, ...]: ...
    def graph_implementation(self, arg_objs, shape: tuple[int, ...], data: Incomplete | None = None) -> tuple[lo.LinOp, list[Constraint]]: ...

class nonneg_wrap(Wrap):
    def is_nonneg(self) -> bool: ...

class nonpos_wrap(Wrap):
    def is_nonpos(self) -> bool: ...

class psd_wrap(Wrap):
    def validate_arguments(self) -> None: ...
    def is_psd(self) -> bool: ...
    def is_nsd(self) -> bool: ...
    def is_symmetric(self) -> bool: ...
    def is_hermitian(self) -> bool: ...

class symmetric_wrap(Wrap):
    def validate_arguments(self) -> None: ...
    def is_symmetric(self) -> bool: ...
    def is_hermitian(self) -> bool: ...

class hermitian_wrap(Wrap):
    def validate_arguments(self) -> None: ...
    def is_hermitian(self) -> bool: ...

class skew_symmetric_wrap(Wrap):
    def validate_arguments(self) -> None: ...
    def is_skew_symmetric(self) -> bool: ...

def validate_real_square(arg) -> None: ...
