from _typeshed import Incomplete
from sympy.external.gmpy import GROUND_TYPES as GROUND_TYPES
from sympy.external.importtools import version_tuple as version_tuple
from sympy.interactive.printing import init_printing as init_printing
from sympy.utilities.misc import ARCH as ARCH

preexec_source: str
verbose_message: str
no_ipython: str

def int_to_Integer(s): ...
def enable_automatic_int_sympification(shell): ...
def enable_automatic_symbols(shell) -> None: ...
def init_ipython_session(shell: Incomplete | None = None, argv=[], auto_symbols: bool = False, auto_int_to_Integer: bool = False): ...
def init_python_session(): ...
def init_session(ipython: Incomplete | None = None, pretty_print: bool = True, order: Incomplete | None = None, use_unicode: Incomplete | None = None, use_latex: Incomplete | None = None, quiet: bool = False, auto_symbols: bool = False, auto_int_to_Integer: bool = False, str_printer: Incomplete | None = None, pretty_printer: Incomplete | None = None, latex_printer: Incomplete | None = None, argv=[]): ...
